model maker Audio: Remove redundant TF function annotation.
This is causing the following warning in the 2.5 release.
AttributeError: 'FuncGraph' object has no attribute '_thread_local'
PiperOrigin-RevId: 371248206